'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowUpRight,Clock,MapPin,Plus,Search} from 'lucide-react';
import {useMemo,useState} from 'react';
import {destinations} from '@/data/destinations';
import type {Dictionary} from '@/i18n/dictionaries';
import type {Locale} from '@/types';
const regions=['all','istanbul','nearby','anatolia','aegean','mediterranean','black-sea'];
export function DestinationExplorer({d,locale='en'}:{d:Dictionary;locale?:Locale}){const [query,setQuery]=useState('');const [region,setRegion]=useState('all');const [added,setAdded]=useState<string[]>([]);const visible=useMemo(()=>destinations.filter(x=>(region==='all'||x.region===region)&&(x.name+' '+x.description).toLocaleLowerCase().includes(query.toLocaleLowerCase())),[query,region]);const add=(id:string)=>{const next=[...new Set([...added,id])];setAdded(next);localStorage.setItem('velora-destinations',JSON.stringify(next))};return <section id="destinations" className="discovery"><header className="discovery-intro"><div><span>11 distinct journeys · one Türkiye</span><h2>{d.dest.title}</h2></div><p>{d.dest.copy}</p></header><div className="discovery-toolbar"><label><Search/><span className="sr-only">{d.dest.search}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={d.dest.search}/></label><nav aria-label="Destination regions">{regions.map(r=><button key={r} aria-pressed={region===r} onClick={()=>setRegion(r)}>{r==='all'?d.dest.all:r.replace('-',' ')}</button>)}</nav></div><div className="destination-mobile-nav">{visible.map(x=><a key={x.id} href={`#destination-${x.id}`}>{x.name}</a>)}</div><div className="editorial-destinations">{visible.map((item,index)=><article id={`destination-${item.id}`} key={item.id} className={`destination-story pattern-${index%3}`}><div className="story-number">{String(index+1).padStart(2,'0')}</div><div className="story-media"><Image src={item.image} alt={`${item.name} — ${item.description}`} fill sizes="(max-width: 800px) 100vw, 62vw" priority={index<2}/></div><div className="story-content"><span>{item.regionLabel}</span><h3>{item.name}</h3><p>{item.description}</p><dl><div><dt><Clock/>Duration</dt><dd>{item.duration}</dd></div><div><dt>Best season</dt><dd>{item.season}</dd></div><div><dt><MapPin/>From Istanbul</dt><dd>{item.travelTime}</dd></div><div><dt>For</dt><dd>{item.travelerType}</dd></div></dl><ul>{item.experiences.slice(0,4).map(x=><li key={x}>{x}</li>)}</ul><div className="program-preview"><small>Journey preview</small><p>{item.program.slice(0,3).join(' · ')}</p></div><div className="story-actions"><Link href={`/${locale}/destinations/${item.id}`}>{d.dest.explore} journey <ArrowUpRight/></Link><button onClick={()=>add(item.id)} aria-pressed={added.includes(item.id)}><Plus/>{added.includes(item.id)?'Added to journey':'Add to my journey'}</button></div></div></article>)}</div>{visible.length===0&&<p className="no-results">No destinations match this view.</p>}</section>}
